### ISSUE TITLE
Control highlight/dehighlight style

### ISSUE THREAD

**Issue by Phrogz** [tintinweb/vscode-interactive-graphviz#179]
I'd love to have settings that control the appearance of the nodes/edges when highlighted or muted. Could be preferences, could be a stylesheet that the preferences open. Instead of manually changing the colors of every edge/node/label that aren't selected, you could simply apply a CSS class to all of them, and let that drive the color, or opacity, or other.

In the SVG in the image below—copied from your output—I've added `select` and `deselect` classes to every `<g class="node">` and `<g class="edge">`.

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/c8268750-5f72-4e4c-b539-84841f3b297b" />

Now, we apply a few different rules:
---

```css
.deselect           { opacity:0.2 }
.edge.deselect text { opacity:0.0 }
```

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/ce641757-dfb6-4e0f-a225-43028c8a9f91" />

---

```css
.select *:not([fill="none"]):not([fill-opacity^="0.00"]) {
    fill:black; fill-opacity:1
}
.select *[stroke]:not([stroke="none"]) {
    stroke:black; stroke-opacity:1.0;
}
.node.select path { fill:yellow !important }
```

<img width="1218" alt="image" src="https://github.com/user-attachments/assets/35dc3be0-de76-433d-9784-3110621b75ab" />

---

```css
.deselect { display:none }
```

<img width="1262" alt="image" src="https://github.com/user-attachments/assets/54a9fbbf-00e0-4fd1-929b-27f164e9077d" />

---

```css
.deselect { opacity:0.4 }
.select.node text { font-weight:bold; fill:black }
.select.edge text { font-weight:bold; fill-opacity:1 }
```

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/328891ad-7b79-4c7e-93f4-25e0b73d3348" />
