### ISSUE TITLE
Theme colors

### ISSUE THREAD

**Issue by bigbug** [tintinweb/vscode-interactive-graphviz#72]
Use the theme's colors as default color for the GV rendering

**Comment by bigbug** [comment]
Is there a "onThemeChanged" in VSCode? This could trigger a re-render.

**Comment by bigbug** [comment]
onDidChangeActiveColorTheme:
[https://github.com/Microsoft/vscode/issues/32813#issuecomment-798680103](https://github.com/Microsoft/vscode/issues/32813#issuecomment-798680103)

**Comment by bigbug** [comment]
Base:
```css
        svg g polygon {
            fill: none;
        }

        svg, svg ellipse, svg path, svg polygon, svg polyline {
            stroke: var(--vscode-foreground);
        }

        svg g.edge polygon {
            fill: var(--vscode-foreground);
        }

        svg text {
            stroke: none;
            fill: var(--vscode-foreground);
        }
```
