### ISSUE TITLE
Restyle toolbars to use theme color

### ISSUE THREAD

**Issue by bigbug** [tintinweb/vscode-interactive-graphviz#80]
The toolbars for the number of search results and the error shall be restyled so that they use VS Code's theme Colors and so that they fit better into the visual appearance.

Base could be:
```css
        .toolbar-danger {
            background-color: var(--vscode-inputValidation-errorBackground);
            border-color: var(--vscode-inputValidation-errorBorder);
            border-style: solid;
            font-size: .9em;
            margin-left: 5px;
            margin-right: 5px;
            margin-top: 3px;
            margin-bottom: 3px;
            padding: 5px;
            border-width: 1px;
        }
```
